### ISSUE TITLE
Parametric nay!

### ISSUE THREAD

**Issue by DrBoolean** [fantasyland/fantasy-monoids#2]
Don't think most of these monoids should have a `map` since they are specific in their value. Yes?

For instance Conjunction must hold a bool

**Comment by DrBoolean** [comment]
By the way, happy to do a PR on these, just wanted to confirm before i do any work

**Comment by SimonRichardson** [comment]
Whoops, wasn't thinking! Just typing away!

Yeap, PR would be ace.
